\---
- name: Run ping  commands B1 Switches when SW03 is offline
  connection: local
  hosts: b1-accsw01
  gather_facts: false
  vars:
    loopbacks:
      b1-distsw01: 10.199.18.3
      b1-accsw01: 10.199.18.21
      b1-accsw04: 10.199.18.24

  tasks:
    - name: run ping to every other host
      ios_command: 
        provider: "{{ creds_core_ssh }}"
        commands: "ping {{ item.value }} source Loopback0 repeat 1"
#      when: item.key != inventory_hostname
      with_dict: "{{ loopbacks }}"
      register: ping_result
      ignore_errors: true


# bepalen de output, dit is nodig om strakt een fail op te kunnen maken als ping fout gaat
    - debug:
       msg: "{{ ping_result.results[1].stdout[0]  }}"

    - name: Fail when not all pings are succesful
      fail: msg="{{ ansible_host }} cannot reach all devices"
#      failed_when: "'rate is 0 percent' in ping_result.stdout_lines[0][4]"
      when: ("'100 percent' not in ping_result.results[1].stdout[0]")

