- name: Create dynamic access-port list
  hosts: b1-accsw01
  gather_facts: no
  tasks:
    - name: Generate access-port  config
      template:
        src: "templates/access-ports-{{ platform }}.j2"
        dest: "{{configs_DIR}}/{{ inventory_hostname}}/{{ inventory_hostname}}.accessports.confg"
      tags: [ accessports, template ]

- name: Install access-port config (always changed)
  hosts: b1-accsw01
  gather_facts: no
  tasks:
    - name: Install access-port config file to access switches
      napalm_install_config:
        provider: "{{ creds_napalm }}"
        config_file: "{{configs_DIR}}/{{ inventory_hostname}}/{{ inventory_hostname}}.accessports.confg"
        commit_changes: "{{ napalm_commit_changes }}"
        replace_config: False
        diff_file: "{{configs_DIR}}/{{ inventory_hostname}}/DIFF/{{inventory_hostname}}.accessports.diff"
      tags: [ accessports, install]

    - pause:
