---
- name: Check BGP neigbor is running on interfaces
  hosts: hq
  gather_facts: no
  vars:
    extra_nb_no: []
  tasks:
    - name: Verify BGP (NAPALM)
      napalm_get_facts:
        provider: "{{ creds_napalm }}"
        filter: bgp_neighbors
      tags: [ bgpnb, validate ]


#    - debug: 
#        msg: "{{ napalm_bgp_neighbors.global.peers }}"

    - set_fact:
        operational_bgp_peers: "{{ napalm_bgp_neighbors.global.peers }}"

#    - debug:
#        msg: "{{ bgp_cur_nb | default ([]) + [ item.key ] }}"
#      with_dict: "{{ operational_bgp_peers }}"

    - name: create shotlist from current BGP neighbors
      set_fact:
        bgp_cur_nb: "{{ bgp_cur_nb | default ([]) + [ item.key ] }}"
      with_dict: "{{ operational_bgp_peers }}"

    - name: Verify BGP neighbors
      assert:
        that: "'{{ item }}' in bgp_cur_nb"
        msg:  "BGP Neighbor {{item}} is missing on host {{ inventory_hostname }}"
      with_items: "{{ bgp_nb_list[inventory_hostname] }}"
      tags: [ bgpnb, validate ]
