- name: Create OSPF config file for HQ
  hosts: hq
  gather_facts: no
  tasks:
    - name: Generate OSPF config
      template:
        src: "templates/igp-{{ platform }}.j2"
        dest: "{{configs_DIR}}/{{ inventory_hostname}}/{{ inventory_hostname}}.igp.confg"
      tags: [ ospf, template ]

- name: Install OSPF config HQ
  hosts: hq
  gather_facts: no
  tasks:
    - name: Test connectivity
      napalm_get_facts:
        provider: "{{ creds_napalm }}"
      tags: [ ospf, connectivity ]

    - name: Install OSPF template to HQ devices
      napalm_install_config:
        provider: "{{ creds_napalm }}"
        config_file: "{{configs_DIR}}/{{ inventory_hostname}}/{{ inventory_hostname}}.igp.confg"
        commit_changes: "{{ napalm_commit_changes }}"
        replace_config: "{{ napalm_replace_config }}"
        diff_file: "{{configs_DIR}}/{{ inventory_hostname}}/DIFF/{{inventory_hostname}}.igp.diff"
      tags: [ ospf, install]

- name: Check OSPF neigbor is running on interfaces
  hosts: hq
  gather_facts: no
  vars:
    extra_nb_no: []
  tasks:
    - name: Get OSPF neighbor
      ios_command:
        provider: "{{ creds_core_ssh }}"
        commands: show ip ospf neighbor
      tags: [ ospfnb, validate ]
      register: ospf_neighbors

    - name: Verify OSPF is running on all internal interfaces
      assert:
        that: "'{{ item }}' in ospf_neighbors.stdout[0]"
        msg:  "OSPF session on interface {{item}} is missing"
      with_items: "{{ ospf_intf_list[inventory_hostname] }}"
      tags: [ ospfnb, validate ]
