---
- name: Create template for BGP
  hosts: localhost
  tasks:
  - name: set hq-r2 A record to DNS"
    nsupdate:
      key_name: "yaworks.demo"
      key_secret: "8THYRPdbhDLU7mNZS0Y7BlhoHDX0d6DiyXzRxEWlFH4y+5QryVS8CCqv A/urP6e9Y+f5v/g+i+bJ8EQ394MKPw=="
      server: "127.0.0.1"
      zone: "yaworks.demo"
      record: "hq-r2"
      value: "10.199.10.2"
